language: cpp
cache:
  - ccache
  - directories:
      - ${HOME}/deps
dist: bionic
addons:
  apt:
    packages:
      - expect-dev # for unbuffer
      - build-essential
      - automake
      - libtool
      - git
  coverity_scan:
    project:
      name: "MrBenGriffin/snaz"
      description: "Snaz"
    notification_email: auto@redsnapper.net
#    build_command_prepend: "<Your build preprocessing command here>"
    build_command: "${TRAVIS_BUILD_DIR}/build.sh"
    branch_pattern: coverity

services:
  - mysql

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - export DEPS_DIR="${HOME}/deps"
  - export LOCAL_DIR="${HOME}/deps/local"
  - chmod 755 *.sh
  - mkdir -p ${LOCAL_DIR}
  - mkdir -p ${DEPS_DIR}/cmake/bin
  - export PATH=${LOCAL_DIR}/bin:${DEPS_DIR}/cmake/bin:${PATH}
  - source ${TRAVIS_BUILD_DIR}/deps.sh travis
  - cd ${TRAVIS_BUILD_DIR}

install:
  - ./build.sh

before_script:
  - mysql -e 'CREATE DATABASE buildtest;'
  - mysql buildtest < ${TRAVIS_BUILD_DIR}/buildtest_edit.sql

script:
  - cd ${TRAVIS_BUILD_DIR}
  - export SQL_CONFIG_FILE=${TRAVIS_BUILD_DIR}/travis.cnf
  - export REMOTE_USER=bgriffin
  - export RS_SITENAME=TestBuilder
  - cmake-build-debug/macrotext -tests
  - mysql --defaults-extra-file=${TRAVIS_BUILD_DIR}/travis.cnf -e 'select purpose,channel,replace(message,"\n"," ") as msg from bldlog order by ts';
  - mysql --defaults-extra-file=${TRAVIS_BUILD_DIR}/travis.cnf -e 'delete from bldlog';
  - cmake-build-debug/macrotext -P
  - mysql --defaults-extra-file=${TRAVIS_BUILD_DIR}/travis.cnf -e 'select purpose,channel,replace(message,"\n"," ") as msg from bldlog order by ts';
  - mysql --defaults-extra-file=${TRAVIS_BUILD_DIR}/travis.cnf -e 'delete from bldlog';


