language: cpp
cache:
  - ccache
  - directories:
      - ${HOME}/deps
dist: bionic
addons:
  apt:
    packages:
      - expect-dev # for unbuffer
      - build-essential
      - automake
      - libtool
      - git
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE buildtest;'
  - mysql buildtest < ${TRAVIS_BUILD_DIR}/buildtest_edit.sql

install:
  - DEPS_DIR="${HOME}/deps"
  - export LOCAL_DIR="${HOME}/deps/local"
  - mkdir -p ${LOCAL_DIR}
  - mkdir -p ${DEPS_DIR}/cmake/bin
  - export PATH=${LOCAL_DIR}/bin:${DEPS_DIR}/cmake/bin:${PATH}
  - source ${TRAVIS_BUILD_DIR}/deps.sh travis

before_script:
  - export LOCAL_DIR="${HOME}/deps/local"
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir cmake-build-debug && cd cmake-build-debug
  - cmake  ..
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}/cmake-build-debug
  - make
  - cd ${TRAVIS_BUILD_DIR}
  - export SQL_CONFIG_FILE=${TRAVIS_BUILD_DIR}/travis.cnf
  - export REMOTE_USER=bgriffin
  - export RS_SITENAME=TestBuilder
  - unbuffer cmake-build-debug/macrotext --color=yes -tests
